### ISSUE TITLE
TypeError after deployment

### ISSUE THREAD

**Issue by sumgup** [alfianlosari/serverless-node-crud-cloud-function#1]
I deployed this Git repo to cloud function, however after deployment if I make a Get/Post request to Notes resource I get this error?

TypeError: Cannot set property path of #<IncomingMessage> which has only a getter
    at App (/user_code/index.js:6:18)
    at /var/tmp/worker/worker.js:726:7
    at /var/tmp/worker/worker.js:709:11
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

Can this be a routing issue?

**Comment by praneethcheedella1** [comment]
Hey did you ever get this issue solved?

**Comment by sumgup** [comment]
> Hey did you ever get this issue solved?

I couldn't resolve it.
